```mermaid
flowchart LR
    subgraph TF-with-modules
        module_ec2_alb_data_aws_ami_mlflow_server_awscday["data.aws_ami.mlflow-server-awscday"]
        module_ec2_alb_aws_iam_instance_profile_ec2_instance_profile_awscday["aws_iam_instance_profile.ec2_instance_profile_awscday"]
        module_ec2_alb_aws_iam_policy_attachment_s3_access_attachment_awscday["aws_iam_policy_attachment.s3_access_attachment_awscday"]
        module_ec2_alb_aws_iam_role_ec2_role_awscday["aws_iam_role.ec2_role_awscday"]
        module_ec2_alb_aws_instance_mlflow_server_awscday["aws_instance.mlflow-server-awscday"]
        module_ec2_alb_aws_lb_alb_mlflow_awscday["aws_lb.alb-mlflow-awscday"]
        module_ec2_alb_aws_lb_listener_http_listener_awscday["aws_lb_listener.http_listener_awscday"]
        module_ec2_alb_aws_lb_target_group_tg_awscday["aws_lb_target_group.tg-awscday"]
        module_ec2_alb_aws_security_group_instance_sg["aws_security_group.instance_sg"]
        module_networking_aws_internet_gateway_gw["aws_internet_gateway.gw"]
        module_networking_aws_route_default_route["aws_route.default_route"]
        module_networking_aws_route_table_public_rt["aws_route_table.public_rt"]
        module_networking_aws_route_table_association_dev_efi_public_association["aws_route_table_association.dev-efi-public_association"]
        module_networking_aws_subnet_private_subnet["aws_subnet.private_subnet"]
        module_networking_aws_subnet_public_subnet["aws_subnet.public_subnet"]
        module_networking_aws_vpc_dev_efi_vpc["aws_vpc.dev-efi-vpc"]
        module_s3_aws_s3_bucket_mlflow_bucket_awscday["aws_s3_bucket.mlflow_bucket_awscday"]
    end
    module_ec2_alb_aws_iam_instance_profile_ec2_instance_profile_awscday --> module_ec2_alb_aws_iam_role_ec2_role_awscday
    module_ec2_alb_aws_iam_policy_attachment_s3_access_attachment_awscday --> module_ec2_alb_aws_iam_role_ec2_role_awscday
    module_ec2_alb_aws_instance_mlflow_server_awscday --> module_ec2_alb_data_aws_ami_mlflow_server_awscday
    module_ec2_alb_aws_instance_mlflow_server_awscday --> module_ec2_alb_aws_iam_instance_profile_ec2_instance_profile_awscday
    module_ec2_alb_aws_instance_mlflow_server_awscday --> module_ec2_alb_aws_security_group_instance_sg
    module_ec2_alb_aws_instance_mlflow_server_awscday --> module_networking_aws_subnet_public_subnet
    module_ec2_alb_aws_lb_alb_mlflow_awscday --> module_networking_aws_subnet_private_subnet
    module_ec2_alb_aws_lb_alb_mlflow_awscday --> module_networking_aws_subnet_public_subnet
    module_ec2_alb_aws_lb_listener_http_listener_awscday --> module_ec2_alb_aws_lb_alb_mlflow_awscday
    module_ec2_alb_aws_lb_listener_http_listener_awscday --> module_ec2_alb_aws_lb_target_group_tg_awscday
    module_ec2_alb_aws_lb_target_group_tg_awscday --> module_networking_aws_vpc_dev_efi_vpc
    module_ec2_alb_aws_security_group_instance_sg --> module_networking_aws_vpc_dev_efi_vpc
    module_networking_aws_internet_gateway_gw --> module_networking_aws_vpc_dev_efi_vpc
    module_networking_aws_route_default_route --> module_networking_aws_internet_gateway_gw
    module_networking_aws_route_default_route --> module_networking_aws_route_table_public_rt
    module_networking_aws_route_table_public_rt --> module_networking_aws_vpc_dev_efi_vpc
    module_networking_aws_route_table_association_dev_efi_public_association --> module_networking_aws_route_table_public_rt
    module_networking_aws_route_table_association_dev_efi_public_association --> module_networking_aws_subnet_public_subnet
    module_networking_aws_subnet_private_subnet --> module_networking_aws_vpc_dev_efi_vpc
    module_networking_aws_subnet_public_subnet --> module_networking_aws_vpc_dev_efi_vpc
```
